"""services/report.py: the standardized interview evaluation report, as Markdown for download."""
from datetime import date

from models import CandidateRecord, EvidenceLevel, JobProfile


def _cell(s: str, n: int = 90) -> str:
    return " ".join((s or "").split()).replace("|", "/")[:n] or "-"


def _bullet(insight) -> str:
    quote = f' (notes: "{_cell(insight.evidence[0].quote, 100)}")' if insight.evidence else ""
    return f"- {insight.statement}{quote}"


def evaluation_markdown(job: JobProfile, rec: CandidateRecord) -> str:
    ev = rec.interview_evaluation
    if ev is None:
        return ""
    name = rec.profile.full_name if rec.profile else rec.candidate_id
    pre = {m.req_id: m.status.value for m in rec.alignment.matches} if rec.alignment else {}
    must = [e for e in ev.evidence_map if e.priority.value == "must_have"]
    must_cov = round(100 * sum(e.level is not EvidenceLevel.NOT_ASSESSED for e in must) / len(must)) if must else 100
    lines = [
        f"# Interview Evaluation Report: {name}", "",
        f"**Role:** {job.title}  |  **Interviewer:** {ev.interviewer or 'n/a'}  |  **Date:** {date.today().isoformat()}", "",
        f"*{ev.decision_note}*", "",
        f"**Coverage:** {ev.assessed_coverage}% of requirements assessed ({must_cov}% of must-haves).", "",
        "## Summary", ev.notes_summary, "",
        "## Requirement evidence",
        "| Req | Priority | Requirement | Resume | Interview | Evidence |",
        "|---|---|---|---|---|---|",
    ]
    for e in ev.evidence_map:
        quote = e.note_excerpts[0].quote if e.note_excerpts else ""
        lines.append(f"| {e.req_id} | {e.priority.value} | {_cell(e.requirement_text, 60)} | "
                     f"{pre.get(e.req_id, '-')} | {e.level.value} | {_cell(quote, 80)} |")
    lines += ["", "## Strengths"] + ([_bullet(s) for s in ev.strengths] or ["- None recorded."])
    lines += ["", "## Concerns"] + ([_bullet(c) for c in ev.concerns] or ["- None recorded."])
    lines += ["", "## Unanswered evaluation areas"] + ([
        f"- **{u.req_id}**: {u.reason}" + (f" Suggested question: {u.suggested_question}" if u.suggested_question else "")
        for u in ev.unanswered_areas] or ["- All requirements were assessed."])
    lines += ["", "## Recommended next steps"] + ([f"- {s}" for s in ev.recommended_next_steps] or ["- None recorded."])
    lines += ["", "---",
              "*Generated by HireFlow from the interview notes. Every quote was checked against the notes. "
              "A human makes the hiring decision.*"]
    return "\n".join(lines)